### ISSUE TITLE
add parameter  --http-proxy=

### ISSUE THREAD

**Issue by mishin** [andk/cpanpm#102]
for example in ruby you can install gem with
gem install yaml-lint --http-proxy=http://username:password@proxy-server.com:3128
so I want to install perl module with
cpan Moo --http-proxy=http://username:password@proxy-server.com:3128

**Comment by mishin** [comment]
sometimes I'm very lazy to tune cpan and
cpan
cpan>  o conf init /proxy/
 Your ftp_proxy? [] ftp://username:password@proxy-server.com:3128
 Your http_proxy? [] http://username:password@proxy-server.com:3128
 Your no_proxy? []
so I  could overwrite my proxy with simple clause 
cpan Moo --http-proxy=http://username:password@proxy-server.com:3128
it give me a big change to make my work faster

**Comment by briandfoy** [comment]
I figure an environment variable would suit you much better. As it is, cpan doesn't do -- switches.

**Comment by mishin** [comment]
well, env variable - ok, thanks

**Comment by briandfoy** [comment]
Also, cpan can load different configuration files with the -j switch.
