### ISSUE TITLE
CPAN module fails tests and won't install (no formatter class)

### ISSUE THREAD

**Issue by Binarus1** [andk/cpanpm#127]
Dear all,

today I tried to upgrade the CPAN module of my Perl installation (Perl 5.24.1, Debian stretch, 64 bit). So I did `perl -MCPAN -e shell` and issued `install CPAN`. Download and make went fine, but the tests failed. In the log, there were multiple messages like the following:

```
# Can't find any loadable formatter class in Pod::Perldoc::Toterm Pod::Perldoc::Toterm Pod::Perldoc::ToTerm Pod::Perldoc::ToTERM Pod::Simple::term Pod::Simple::term Pod::Simple::Term Pod::Simple::TERM Pod::term Pod::term Pod::Term Pod::TERM Pod::Perldoc::Totext Pod::Perldoc::Totext Pod::Perldoc::ToText Pod::Perldoc::ToTEXT Pod::Simple::text Pod::Simple::text Pod::Simple::Text Pod::Simple::TEXT Pod::text Pod::text Pod::Text Pod::TEXT Pod::Perldoc::ToPod?!
# Aborting
#  at -e line 1.
# '
#     doesn't match '(?^m:^[ ]+-x)'

#   Failed test 'advertizing X'
#   at t/97-run.t line 28.
#                   'Using logger from Log::Log4perl::Logger
# Hooked into output
# Patched cargo culting
# Options are $VAR1 = {
#           'h' => 1
#         };
# Use perldoc to read the documentation
```
In consequence, the module refused to install. I got around the problem by using `fforce install CPAN`, but this is unsatisfactory as it could hide _real_ problems.

Before opening this issue, I have put two hours in researching the problem via Google. There are lots of reports of exactly the same problem, from the past several years. No solution given so far cured the problem in my case.

I have checked that at least some of the modules which are claimed to be missing are actually installed, so this can't be the problem. For example, Pod::Text is definitely installed although the error message says it's not.

I have *one* Perl installed and didn't change too much on that system yet. It's nearly a Debian stretch stock system. Hence, I do not believe that the issue is related to path settings, wrong library versions or the like; please correct me if I am wrong.

What am I doing wrong?

Thank you very much for the CPAN module!

Regards,

Binarus

**Comment by andk** [comment]
Thank you for your report. Is it possible that you are running the cpan shell as the root user? Please don't. If you don't please provide more insight about your system, so I can try to make another educated guess what might cause the test to fail.

**Comment by Binarus1** [comment]
Thank you very much for taking the time.

You are completely right: I am running the CPAN shell as the root user. I have not tried to run it as a normal user yet, for the following reasons:

- Previous CPAN versions did not have that problem. In the past, I have updated CPAN from within the shell multiple time without any issue, even when the shell ran as root.

- I would like to install modules system-wide; as far as I have understood, when I run CPAN as normal user, the modules will be installed / updated in the user's home directory, which is not what I want.

- Sudo doesn't help either: If I am a normal user and start the CPAN shell as root, the I'll be root from the shell's point of view, leading to the same problem.

So what would be the correct way to install CPAN (and other modules) system-wide?

Regards,

Binarus

**Comment by andk** [comment]
Thanks for coming back to me, I'm glad you confirm my diagnosis, so I can go on to prepare the next release and get rid of this failing test.

The failing test will be skipped in the next release when called by the root user, so if you like to run the cpan shell as root, you can continue to do so and will not be disturbed by this test failing. It's just not the way for the faint of heart.

For learning about how you can combine the cpan shell with sudo, maybe read the `CPAN::FirstTime` manpage and search for `make_install_make_command` and `mbuild_install_build_command`. Or run

```
 o conf init /install_.*_command/
```

to set them both interactively immediately.

Thanks again, I'm closing this issue, feel free to reopen or open a new one when questions remain,

**Comment by Binarus1** [comment]
Thank you very much again for taking the time. I am very happy that this problem will be fixed. In the meantime, I'll study the man pages you mentioned and I'm looking forward to learn something new.

Once again, thank you very much for your help.
