### ISSUE TITLE
Configure with only fresh mirrors

### ISSUE THREAD

**Issue by briandfoy** [andk/cpanpm#141]
I've been having trouble with various CI systems lately because I let CPAN.pm auto configure itself (for instance, [this run on PerlPowerTools](https://github.com/briandfoy/PerlPowerTools/runs/1184674267?check_suite_focus=true#step:6:39)). Sometime it selects dead mirrors. _MIRRORED.BY_ lists _http://mirrors-usa.go-parts.com/cpan/_ as a mirror. _http://mirrors.cpan.org/cpan-json.txt_ notes this mirror has a last good date on (Fri Jul 12 16:22:05 2019). [_MIRRORED.BY_](https://www.cpan.org/MIRRORED.BY) itself was last updated (Thu Dec 12 17:30:03 2019). However, _http://mirrors.cpan.org/cpan-json.txt_ was updated just today.  _http://mirrors-usa.go-parts.com/cpan/_ is still in there but is obviously stale.

So, what creates _MIRRORED.BY_? Is it still running? Should this be a PAUSE issue instead?

**Comment by briandfoy** [comment]
I'd still like some answers, but @rspier fixed the _MIRRORED.BY_. There was a syntax error in one of the input files, so I guess that tripped up whatever was automatically making that file. There's now a fresh version on CPAN.

However, the fresh version still has the bad _http://mirrors-usa.go-parts.com/cpan/_.

**Comment by rspier** [comment]
@briandfoy As mentioned in email, the mirror list infrastructure is not getting appropriate care and feeding right now.

This isn't a PAUSE or CPAN.pm problem.

Our recommendation is to NOT let CPAN.pm autoconfigure itself, but to use https://www.cpan.org/ everywhere.  That's cached in hundreds of locations on fast net.

To fix your immediate mirrors-usa.go-parts.com, I've marked it as retired.  It should drop from the data files soon.

**Comment by briandfoy** [comment]
@rspier Where did you mark it as retired? When I looked in the cpan-mirrors-data repo, there wasn't an entry for it. Did you have to make an entry in mirrors.json just to mark it retired? I'm still trying to figure out how all of this works.

I'd be fine using https://www.cpan.org everywhere, but doing this non-interactively with legacy CPAN.pm for old Perl version is in CI systems doesn't give me a lot of palatable options.

**Comment by rspier** [comment]
See 525b8ca in cpan-mirrors-data.  There was an entry.

Couldn't you just have the CI pipeline write out the appropriate CPAN config file before doing installation?

**Comment by briandfoy** [comment]
I (and others) could do all sorts of things, but I'd rather fix the problem that I'm working around.

And, it's not just what I personally can do. It's what all of the world has to do when they don't know how things work or why they are getting an error.
