### ISSUE TITLE
`cpan -T somemodule` runs the tests anyway on OSX

### ISSUE THREAD

**Issue by chdiza** [andk/cpanpm#74]
If I understand the docs correctly, doing `cpan -T somemodule` on the commandline should just install the module `somemodule` without running tests, as if one had done `cpan`, followed by `notest install somemodule`.

However, on OSX (all versions, starting with 10.4 up through 10.9) and any version of perl starting at 5.14, any tests associated with `somemodule` get run anyway, as if I never passed `-T` on the commandline.

**Comment by briandfoy** [comment]
You have to have a supported version of the cpan(1) program and a version of CPAN.pm that supports it. The stuff that Apple ships is probably a couple years behind current versions due to their long lead time on acceptance testing.

If you have a version that supports -T (by noting it in the docs), include that info here. 

Also, we won't be able to fix older distributions. The only good answer is to upgrade CPAN.pm.

**Comment by chdiza** [comment]
Is 2.05 not the current version?  I have perl 5.20.1 installed, and even there, `-T` doesn't actually do anything.

The `cpan` that does come with OSX 10.10.2 does *claim* to support `-T`, since it's in `man cpan` over here.

**Comment by briandfoy** [comment]
Can you show the output of cpan -V? The first thing you should nail down is
the versions of everything you are using.

Can you also show some output you get from trying this? Include the command
you use. The more information you can supply the easier it is for me to see
what's happening.

**Comment by chdiza** [comment]
OSX 10.10.2...

`cpan -V` gives:
```
cpan -V
Use of uninitialized value $rtt in multiplication (*) at /Applications/z/pl/lib/perl5/5.20.1/App/Cpan.pm line 863.
Trying to fetch a mirror list from the Internet
Fetching with HTTP::Tiny:
http://www.cpan.org/MIRRORED.BY

CPAN::Mirrors->new requires a filename at /Applications/z/pl/lib/perl5/5.20.1/App/Cpan.pm line 695.
```

`perl --version` gives:
```
perl --version

This is perl 5, version 20, subversion 1 (v5.20.1) built for darwin-thread-multi-2level
```
The version of CPAN.pm carried in perl 5.20.1 is "2.05".

The command(s) that show that `cpan -T` runs tests is `cpan -T anything-that-has-tests`.  I notice it when I run the following:
```
cpan -T Curses::UI
cpan -T MIME::Parser
cpan -T HTML::Parser
```
You can see the entire output for the last of those three in [this gist](https://gist.github.com/chdiza/6360d996b4c154378859).  It's loaded with tests, the first batch of which begin on line 45.  Perhaps the `-T` option isn't being applied to auto-downloaded deps?

For the record, if i do `cpan` and hit return to get into the CPAN shell, then doing `notest install foo` works just fine.

You can close this if you want; I switched to `cpanminus` last month precisely because it doesn't have this problem.

**Comment by briandfoy** [comment]
Okay, thanks. I think this might have been fixed since you reported this. I haven't been able to reproduce it on OS X with the current sources.

Thanks again,
