### ISSUE TITLE
CPAN Pull Request Challenge

### ISSUE THREAD

**Issue by cabrinha** [andk/cpanpm#93]
Hi,

I've been assigned CPAN as part of the [CPAN Pull Request Challenge](http://cpan-prc.org/)... for August :)

I've looked through RT and GitHub tickets trying to find anything that I could turn into a PR, but so far don't see anything that could be done by a perl newbie, like me.

Do you have any suggestions?

Let me know,
Scott

**Comment by briandfoy** [comment]
I'm sorry for the delay in responding. There's issue #97 that I think comes from a restricted reading of the script/cpan docs. In the Exit Status section (or whatever it is called), there's one exit value marked as "a module failed to install". Some people may read that as one of the modules specified on the command line, but it actually means any module including dependencies and recommended modules. You cold dust the docs for that.

If you've moved on in the challenge, you can indicate that we can close this issue. Thanks for taking part although we dropped the ball on getting back to you. 😿
