### ISSUE TITLE
cpan -O fails to run

### ISSUE THREAD

**Issue by xxfelixxx** [andk/cpanpm#98]
$  cpan -O
    CPAN: Storable loaded ok (v2.51)
    Reading '/home/felix/.cpan/Metadata'
      Database was generated on Sat, 02 Jul 2016 08:41:02 GMT 
    Module Name                                Local    CPAN
    -------------------------------------------------------------------------
    Can't locate object method "inst_file" via package "AAA::Demo" (perhaps you forgot to
    load "AAA::Demo"?) at /usr/local/share/perl/5.20.1/App/Cpan.pm line 1339.

    App::Cpan ( Version 1.64 )
    -------------------------------------
    1330  sub _show_out_of_date
    1331          {
    1332          my $modules = _get_all_namespaces();
    1333  
    1334          printf "%-40s  %6s  %6s\n", "Module Name", "Local", "CPAN";
    1335          print "-" x 73, "\n";
    1336  
    1337          foreach my $module ( @$modules )
    1338                  {
    1339                  next unless $module->inst_file;
    1340                  next if $module->uptodate;
    1341                  printf "%-40s  %.4f  %.4f\n",
    1342                          $module->id,
    1343                          $module->inst_version ? $module->inst_version : '',
    1344                          $module->cpan_version;
    1345                  }
    1346  
    1347          return HEY_IT_WORKED;
    1348          }

It looks like the issue is that @$modules is returning a list of module names as strings, but inside the for loop, it is expecting Cpan::Module objects.

Suggested patch:

    1337c1337
    < 	foreach my $module ( @$modules )
    ---
    > 	foreach my $module_name ( @$modules )
    1338a1339,1340
    >         my $module = _expand_module( $module_name );
    >         next unless $module;

**Comment by sboss** [comment]
making this change fixed my issue with CPAN on Windows.

**Comment by andk** [comment]
Thanks a lot for your effort, but please give 2.15-TRIAL a chance, it has this and more already fixed.

**Comment by xxfelixxx** [comment]
Closing as this has already been fixed.  Thanks!
